### ISSUE TITLE
User Journey: As an un-organized person I want to set up my goals in an easy and simple UI

### ISSUE THREAD

**Issue by antoniotrkdz** [FAC10/goalTracker#1]
so that they are all in an **single place**, **easy to follow** and work towards.

**User Stories**
- [ ] #3 As a user I can choose from one of 5 broad goal categories
- [ ] #7 As a user who has selected a category I can add a new goal within that category
- [ ] #8 User can add a goal title 
- [ ]
